import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from "react";
import styles from '../styles/Home.module.css'
import SitesName from '../components/SitesName';
import { CountProvider, useCount } from "../context";
export default function Home() {
const [data , setData] = useState([])
const { increment, count, decrement } = useCount();


useEffect(() => {
  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': 'db9b492084mshf3cdbb6462cbd91p1793f7jsn202fbc065f4a',
      'X-RapidAPI-Host': 'quality-porn.p.rapidapi.com'
    }
  };
  
  fetch(`https://quality-porn.p.rapidapi.com/search?query=amateur&quality=hd&page=${count}`, options)
    .then(response => response.json())
    .then(response => setData(response))
    .catch(err => console.error(err));

}, [count])

console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <SitesName data={data.data}/>
      </main>


    </div>
  )
}


Home.provider = CountProvider;